# Kubernetes deployment configuration for SIH AI Harvesters Platform
# For cloud deployment on platforms like GKE, EKS, or AKS

apiVersion: v1
kind: Namespace
metadata:
  name: sih-ai-harvesters

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sih-ai-harvesters
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sih-ai-harvesters
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/sih_ai_harvesters"
  GEMINI_API_KEY: "your-gemini-api-key"
  REDIS_PASSWORD: "your-redis-password"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sih-ai-harvesters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "sih_ai_harvesters"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sih-ai-harvesters
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sih-ai-harvesters
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sih-ai-harvesters/api:latest
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: sih-ai-harvesters
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sih-ai-harvesters
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sih-ai-harvesters/frontend:latest
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://your-domain.com/api"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sih-ai-harvesters
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: sih-ai-harvesters
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
  - hosts:
    - your-domain.com
    secretName: app-tls
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sih-ai-harvesters
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
